Update The Silver Steed and The Many-Faced God to their errata´d versions
throneteki/throneteki-json-data pull request #155
Opened 2024-01-23 16:18 UTC by EvadLhorg

ToDo: Add link for the errata, the card.schema is validating this

2024-01-24 01:31 UTC, Patane97 approved these changes
Looks good, although we will need to update the `imageUrl` of The Silver Steed once we get the images uploaded. That is a low priority task though, so we can do it in a separate Pull Request after the images are actually uploaded. :)

2024-01-24 17:21 UTC, stopfstedt requested changes
the errata sections look good, but the cards' primary texts needs to be realigned with the changes from their last erratum.

2024-01-24 17:21 UTC, stopfstedt commented on packs/HMW.json
>              "text": "Your plot deck cannot include <i>Kingdom</i> plot cards.\nReduce the cost of the first card you ambush each round by 1.\n<b>Action:</b> Kneel your faction card to choose a charac
needs to be updated with the v2.0 text.

2024-01-24 17:21 UTC, stopfstedt commented on packs/TKP.json
>              "text": "<i>Dothraki</i> character or Daenerys Targaryen only.\nWhile attached character is participating in a [power] challenge, it gains renown.\n<b>Reaction:</b> After attached charact
needs to be updated with the v2.0 text.

2024-02-04 18:03 UTC, stopfstedt approved these changes
pushing this over the finishing line.

2024-02-04 18:03 UTC, merged